# Generated by Django 6.1.1 on 2026-10-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Livres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cahiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
